### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by bring728** [sguttikon/SFSS-MMSI#3]
hi! thanks for sharing your excellent work! 

could you please release the pretrained model??

**Comment by sguttikon** [comment]
Please refer the [Readme.Md](https://github.com/sguttikon/SFSS-MMSI/tree/main?tab=readme-ov-file#result)

**Comment by bring728** [comment]
Oh, I see. Sorry I didn't notice. I thought it was a link to download the dataset.
